"""add_initiative_type_field

Revision ID: a31e32b87734
Revises: bc53afee9798
Create Date: 2026-01-20 15:32:23.105606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31e32b87734'
down_revision: Union[str, Sequence[str], None] = 'bc53afee9798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combat_sessions', sa.Column('initiative_type', sa.Enum('INDIVIDUAL', 'GROUP', 'SIDE', 'REROLL', name='initiativetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combat_sessions', 'initiative_type')
    # ### end Alembic commands ###
