"""add_death_saving_throw_fields

Revision ID: b13b827c08fb
Revises: a72f4afd4a9e
Create Date: 2026-01-20 15:23:44.696946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13b827c08fb'
down_revision: Union[str, Sequence[str], None] = 'a72f4afd4a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('death_save_successes', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('death_save_failures', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('is_stable', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_stable')
    op.drop_column('characters', 'death_save_failures')
    op.drop_column('characters', 'death_save_successes')
    # ### end Alembic commands ###
