"""add_monster_id_field

Revision ID: bc53afee9798
Revises: b13b827c08fb
Create Date: 2026-01-20 15:28:00.408487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc53afee9798'
down_revision: Union[str, Sequence[str], None] = 'b13b827c08fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('monster_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'monster_id')
    # ### end Alembic commands ###
